#! /bin/bash

# runwithpkexec
#
# simplest script wrapper to expose any command(s) to Polkit under the name 'runwithpkexec'
#
# Copyright (C) 2018  Alexandru-Catalin Petrini (alexandru.c.petrini@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.

# This program is distributed in the hope that it will be useful,# # #
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

exec "$@"
